### ISSUE TITLE
make behat scenarios more granular

### ISSUE THREAD

**Issue by Ma27** [Sententiaregum/Sententiaregum#340]
### Description

In order to do "real" BDD, we should try to step away from a technical language in behat to a specification language which describes workflows of how to receive data (the ReactJS frontend is basically just a UI for those workflows defined as API).

To achieve that, some last steps are necessary to achieve this.
### Tasks
- [x] create a project root dir for the features (`features/`) as it's rather a description and not something technical
- [x] rename subdirs:

```
- api
  - {resource}
    - {feature}
- data
  - {resource}
    - {feature}
```
- [x] split files to segregate every feature (also on the data layer)
- [x] checkout whether more granular steps are possible
- [x] test REST APIs directly (this avoids useless feature contexts)
