### ISSUE TITLE
as a user I'd like to enter my credentials in order to access my social dashboard

### ISSUE THREAD

**Issue by Ma27** [Sententiaregum/Sententiaregum#35]
**Tasks:**
- [x] api for getting credential details of users after login
- [x] login interface
- [x] improve the user model (reduce public API, make validation more strict and couple logic better onto the models)
- [x] stop usage of `http` services in the business logic and prefer fetching the store states
- [x] basic dashboard skeleton (logout + handler for auto-logouts + redirect service for logins)

**Comment by Ma27** [comment]
@benbieler would you like to do this? We have to talk a bit about some details, but as it will be 95% javascript (some php because of another credential api as we need some features the ApiKeyAuthenticationBundle doesn't support).

**Comment by Ma27** [comment]
ok, this issue is a blocker and now blocked by the other tasks^^
Man this shit sucks
