### ISSUE TITLE
upgrade to php 7.1 and symfony 3.2

### ISSUE THREAD

**Issue by Ma27** [Sententiaregum/Sententiaregum#350]
### Description

there are various RCs for 7.1 and it won't take too much time until PHP 7.1 is ready.
I'm in favor of upgrading just for the sake of dropping PHP 7.0 as the lack of nullable types is just annoying in certain cases.

### Tasks

- [x] ensure latest packages (PHP 7.1, Symfony 3.2, PHPUnit 5.7)
- [x] keep code-base up-to-date
  - [x] use types everywhere (e.g. void or nullable if not already present)
  - [x] drop `list()` usage for new `[]` syntax
  - [x] make constants private when possible
  - [x] use `Closure::fromCallable` rather than `$that = &$this;`. (In the `OnlineUserIdCluster` a dependency needs to be injected into a callback. This can be simplified to avoid these dirty `$that` hacks)
- [x] keep phpunit tests up-to-date
  - [x] use `createMock` everywhere
- [x] keep symfony-related code up-to-date
  - [x] use `ConstraintValidatorTestCase` rather than legacy `AbstractConstraintValidatorTest`

**Comment by Ma27** [comment]
didn't add a milestone for now as I'm not sure whether PHP 7.1 will be released before `0.1`
