### ISSUE TITLE
Rewrite of the platform's frontend

### ISSUE THREAD

**Issue by Ma27** [Sententiaregum/Sententiaregum#353]
### Introduction

I'm currently working on several OSS packages (Ma27ApiKeyAuthenticationBundle, puppet-nodejs, puppet-composer and all the Sententiaregum-related stuff). Unfortunately I'm currently lacking more and more time, but some packages have a higher priority (the puppet modules for instance), so it's hard to maintain our current flux API properly.

Another reasons why I consider a rewrite is that we tried to figure out a great architecture during the whole year (just see all the refactoring commits). And I found (again) some aspects that needs fixing/improvement and I fear that this will end up in a never-ending cycle. Therefore I'd suggest to gather certain aspects and analyse them before deciding which refactorings should be done which parts can be left as-is.

### ReactJS

ReactJS is fine, well-maintained and does a great job. Shouldn't be necessary to discuss about it.

### Redux?

I'm currently thinking about abandoning our flux API and move to Redux. I'm lacking resources to maintain it properly and thanks to Redux's architecture it has certain advantages over Flux like the ability to do time-travel debugging and it's much easier to compose functions (reducers in Redux context) which is helpful with recurring problems like pagination of arrays (and adopts FP patterns much better than our current API).

Furthermore we should keep in mind that redux basically consists of [99 lines of code](https://gist.github.com/gaearon/ffd88b0e4f00b22c3159) which means that it's much more lightweight than our library (even simpler than the very first version of our library).

### `styled-components`?

This library uses the approach of template-string tagging (new feature in ES6) to make better styling for components.
This is a more pragmatic, declarative approach to style certain components.

On the other hand this uses lots of inline-styling which is considered to be harmful and should be avoided.

### `react-router`?

I think that this is a great library which could be still used.

Some weeks ago the creators started the progress on [a new major version](https://github.com/ReactTraining/react-router/releases/tag/v4.0.0-0). The big advantage is that this new version aims to provide a more declarative API (which is also good in context of FP), but it's still in alpha stage so we should discuss whether or not to use it (and refactor code in the next months after the release).

### Tasks

- [x] Improve Webpack config (@benbieler)
- [x] Simple redux implementation (@benbieler)
- [x] Remove obsolete `LocaleController::getSupportedLocalesAction` (@benbieler)
- [x] Improve eslint configuration to comply with our new coding style (@Ma27)
- [x] Get rid of massive switch-case blocks (@benbieler)
- [x] Refactor security system (HOC) (@Ma27)
- [x] change mail adresses (@benbieler)
- [ ] `nix-shell` should include NPM dependencies (@Ma27)
- [ ] Registration page (@benbieler, @Ma27)
  - [x] kill shrinkwrap (@Ma27)
- [ ] Activation page (@benbieler)
- [ ] Login (@Ma27)
- [ ] Logout/Dashboard (@Ma27)
- Frontend Maintenance
  - [ ] update docs for redux architecture (`docs/architecture/frontend.md`) (@Ma27)
  - [ ] refactor frontend testing aliases (@Ma27)
  - [ ] Deprecate flux container (remove dependencies and related files, move flux-container to `sen-legacy` org) (@Ma27)
  - [ ] Remove hashHistory -> browserHistory (@Ma27)
- [ ] Add styled components (@benbieler)

**Comment by Ma27** [comment]
I think one of the first things to work on should be the webpack:

it's working quite fine ATM, but the watching screws up (at least on my machine). @benbieler could you confirm that the watcher is broken on your machine, too?

**Comment by mxstbr** [comment]
> On the other hand this uses lots of inline-styling which is considered to be harmful and should be avoided.

Just to chime in here, `styled-components` actually inject actual CSS into the DOM, meaning everything you expect from CSS works perfectly fine since it's just CSS! For example:

```JS
const Wrapper = styled.section`
  max-width: 750px;
  width: 100%;
  margin: 0 auto;

  &:hover {
    background-color: blue;
  }

  @media screen and (min-width: 1000px) {
    max-width: 1250px;
  }
`
```

If you have any `styled-components` related questions, feel free to ping me! 😊

**Comment by Ma27** [comment]
thanks @mxstbr for your answer.

We're currently trying to evaluate which frontend tools to use in the future and which not.
The thing is, I know that `styled-components` won't have any different behavior than "normal" css, but it reminds me of this inline styling using a `style` attribute and that's the reason why I'm unsure whether to use it.

On the other hand I highliy appreciate the ES6 syntax used in there and I can imagine (at least) two places where this might be very useful.

> If you have any styled-components related questions, feel free to ping me! 

Thanks a lot for this offer :)

**Comment by benbieler** [comment]
Well @Ma27 first of all:  I can **not** confirm that the webpack watcher does not work. 

Generally I agree with your proposals: 

- [x] Redux
- [x] React-router
- [x] Webpack

When it comes to styling, the other day I read the following article: http://jamesknelson.com/why-you-shouldnt-style-with-javascript/  which raises questions regarding this.

I would just (for now) stick with the normal bootstrap stuff, and move this to the lowest Prio of the mentioned issues, that are to tackle ^^.

**Comment by mxstbr** [comment]
> When it comes to styling, the other day I read the following article: http://jamesknelson.com/why-you-shouldnt-style-with-javascript/ which raises questions regarding this.

Just to note, none of the problems mentioned in that article (except for caching) is an actual issue with `styled-components`.

We have support for global style injection with `injectGlobal` for things like `@font-face`, we don't claim to remove inheritance and we let you write actual CSS so you're just using CSS, meaning your designers can write it and we don't actually override everything because it's not inline styles, it's CSS-in-JS.

Instead of attaching styles to DOM nodes into the style tag, we allow you to write actual CSS but augment it with JavaScript.

I totally understand if you are not going to use `styled-components`, to each their own. But that article linked does not apply to it at all.

**Comment by benbieler** [comment]
@mxstbr Thanks for your quick response.

> Just to note, none of the problems mentioned in that article (except for caching) is an actual issue with styled-components.

I agree. The article I referenced obviously does not have a lot to do with your react module, it was a general point of mine.

But nonetheless I would recommend to deal with the styling aspect last. But I guess we could give styled-components a try. It seams like a cool module, so no offence ;)

> I think one of the first things to work on should be the webpack

This for example is way more important to get a working webpack config (on both ;) ) machines.

**Comment by Ma27** [comment]
@mxstbr thanks for pointing that out. As @benbieler already mentioned, this is an aspect to talk about, but has less priority than other stuff in our frontend.

>  I can not confirm that the webpack watcher does not work.

I think that I found the actual issue: whenever I ran all the NPM scripts in my IDE, the watcher screwed up, but it seems to work when being on the bash itself.

Another aspect regarding webpack is the update to webpack2 (not sure if there's a stable release already).

> react-router

should we directly start using v4 (https://github.com/ReactTraining/react-router/releases/tag/v4.0.0-alpha.6). It's alpha stage, but the migration seems to be painful as a lot of things changed and it looks quite cool ([this for instance](https://github.com/ReactTraining/react-router/blob/v4/website/examples/Basic.js)).

> Redux

Yep, I think that when we gathered all the aspects to work on, we should start a more detailed discussion about the redux architecture (auth flow with redirects needs to be evaluated)

Another aspect to talk about is the usage of a form library: some months ago I tried to deduplicate all the stuff inside of our components, it does its job, but I'm not a big fan of some parts regarding the design.

Do you know any suitable form library or sth. like this? Some time ago I wrote a proposal of how a form library might look like (https://gist.github.com/Ma27/eca252a16ac27b2f4ce755a5d091ffcd).

**Comment by Ma27** [comment]
did some research regarding the form library: As Redux is a predictable state container it's a good practice to make it the only source of data in our application (therefore I'd suggest to use `react-router-redux` for routing).

Yesterday I found the following package: https://github.com/erikras/redux-form

It's quite neat since it uses redux for state management and uses one of Redux's biggest advantages, the usage of stateless components: we can do this from time to time as well right now, but our forms don't work well with this.

This is the most flexible library I've seen so far, so we might be able to keep our high-level form components (https://github.com/Sententiaregum/Sententiaregum/tree/master/src/Frontend/components/form) and rewrite their internals to make the compliant with `redux-form`. As this library supports the injection of components as well into their API (`<Field component={...} />`) we it should be easy to continue using the markup API of `react-bootstrap` for our forms.

Anything to add here @benbieler? Unless, I'd say that we can finalize the discussion about the forms, the router and webpack and continue with redux and research if there's anything to improve in our React code :)

**Comment by benbieler** [comment]
@Ma27 
> therefore I'd suggest to use react-router-redux for routing.

Well I use `react-router-redux` at work, and really like it.  The other stuff seems fine to me.

**Comment by Ma27** [comment]
@benbieler thanks a lot for your recommendation.

In order to summarize so far:

- use `react-router@4.x-alpha` because of it's new, declarative approach and `react-router-redux`
- according to [this tweet](https://twitter.com/mxstbr/status/803244148337713156) webpack is almost ready and some of the [new features](https://gist.github.com/sokra/27b24881210b56bbaff7) seem to be quite nice
- use `redux-form` as it uses redux for statemanagement internally and is quite flexible. Furthermore we might be able to keep our current internal form components and just change the internals of this components.
- maybe use `styled-components` for our markup components like the `InversedGrid` or some dropdown components (to be discussed when we talked about everything else)

Due to the fact that `axios` does its job quite well, we decided to use `redux` and I'm happy with our current testing approach, so there shouldn't be too much discuss anymore.

When there's enough time @benbieler I'd propose that we talk about some architecture details and gather all tasks to be done and then start with the progress of all of these tasks somewhere around christmas :)

**Comment by mxstbr** [comment]
> according to this tweet webpack is almost ready and some of the new features seem to be quite nice

Sorry to annoy you again, just want to mention that I've been using webpack v2 in production for a good 4-5 months now, and it's also been in `react-boilerplate` for the same amount of time. It's ready to be used!

**Comment by Ma27** [comment]
yeah, seen it (that some folks already use it in production).
But I have to admit that I'm quite hesitant to use unstable software and due to the fact that "docs" seem to be a blocker and I'm unsure whether or not that's an impact.

**Comment by Ma27** [comment]
so it seems as `redux` is one of the remaining things to be talked about:
There are several things to be validated:

- what happens if we redirect during the evaluation of a redux action? (This was the issue where the original flux dispatcher screwed up)
- how to structure redux? It's basically a state container, but we should find a good solution how to structure everything (here are some [examples](https://github.com/reactjs/redux/tree/master/examples))

another thing that needs a little bit evlauation is the current internal service API (https://github.com/Sententiaregum/Sententiaregum/tree/master/src/Frontend/util/http). I don't really like the stuff in there and I'll think about how to remove that entirely.

**Comment by Ma27** [comment]
> Well I use `react-router-redux` at work

@benbieler as you use `redux` at work, is there anything special to be talked about (what I'm missing) or something we need to look at? (Don't want to mess up the frontend (again))

**Comment by Ma27** [comment]
Just to chime in here again: we started building a simple redux-based setup and currently most of the wrappers (Menu, Application, Security and Locale) work again and have passing tests. The only missing thing are the routes right now.

**Comment by videni** [comment]
It seems that the [ApiPlatform](https://api-platform.com/)  is quite good for SPA,  suggest you to  try this to write your REST API.

**Comment by benbieler** [comment]
@videni We aren't going to rewrite the REST backend.

**Comment by Ma27** [comment]
According to the repository the `1.0.0` of api-platform has been tagged in September of 2015 and AFAIK it took some time until it became as popular is it is nowdays.

But at that time Ben and I started coding and we used a proven set of libraries for the backend (FOSRest, latest Symfony, etc) which is still well-designed and well-maintained.
As you can see we had good reasons to start a refactoring (hopefully we'll manage to spend some time in summer to work on it), but I don't think that we'll manage to build anything useful here when also doing a rewrite of the backend.
