### ISSUE TITLE
symfony 3.0 upgrade

### ISSUE THREAD

**Issue by Ma27** [Sententiaregum/Sententiaregum#44]
**Tasks:**
- [x] refactor version constraints for symfony3
- [x] fix upcomming deprecations
- [x] use new directory structure

**Comment by Ma27** [comment]
the following bundles must be removed:
- Sonata Notification/Core/Datagrid/EasyExtends (#130)
- Lunetics Locale (the actual reason of the bundle are features such as the switcher. We just need a cookie listener for the locale which can be done by ourselves)
- JMS DiExtra (because of a lack of maintenance, instead of much boiler plate code the services.yml can be loaded in the Bundle#build() method which will be executed right before applying the extension in the boot workflow)

**Comment by Ma27** [comment]
added low priority label as we're currently on `2.8` which is a LTS release, so we have time :)

**Comment by Ma27** [comment]
the `SncRedisBundle` is missing a stable 3.0 release.
After that we can go for it

**Comment by Ma27** [comment]
ok, SncRedisBundle is ready, Sonata environment has been removed thanks to @benbieler, JMSDiExtra has been removed because of missing support for factories (necessary when implementing doctrine respositories and blocker for this and #296).
