### ISSUE TITLE
drop php5 support

### ISSUE THREAD

**Issue by Ma27** [Sententiaregum/Sententiaregum#46]
when the release of php7 comes, we should drop the support of php5 in order to gain better performance and having all the php7 features.
As we don't have any releases yet and we should do that before releasing the 1.0.0 we won't have any support issues.

**Tasks:**
- [x] update version constraints
- [x] refactor travis build environment
- [x] use php7 in vagrant
- [x] new php7 language features (https://github.com/dunglas/phpdoc-to-typehint)
- [x] use ocramius/proxy-manager v2

**Comment by Ma27** [comment]
btw we can use phpunit 6.0 then: sebastianbergmann/phpunit#1751

**Comment by Ma27** [comment]
blocked by #44
